# ======================================================================
# PPTree Visualization
#
# Native ggplot2 rendering for PPTree and PPForest models.  Provides:
#   - Tree structure diagram with embedded class histograms at each node
#   - Variable importance bar chart (projection, weighted, permuted)
#   - Projection histogram at any split node
#   - Decision boundary plots (1D, 2D, and pairwise for p > 2)
#   - Mosaic layout combining structure + importance + boundaries
#
# All plots use a shared design system (constants below) for cohesive
# styling.  Data-mapped colors (class fill/colour) use ggplot2 scales
# so users can override them with + scale_fill_manual(...).
#
# Architecture:
#   - C++ (Visualization.hpp/cpp) computes geometry: node data routing,
#     boundary line clipping, region polygon clipping (Sutherland-Hodgman),
#     and tree layout positioning.
#   - R (this file) handles rendering: translates C++ output into ggplot2
#     layers and assembles composite layouts via the grid package.
# ======================================================================

# Suppress R CMD check NOTEs for ggplot2 aes() column references
utils::globalVariables(c(
  "from_x", "from_y", "to_x", "to_y",
  "importance", "variable",
  "projected", "class",
  "x", "y",
  "x_start", "y_start", "x_end", "y_end",
  "alpha",
  "edge_label", "group", "xmin", "xmax", "ymin", "ymax", "label",
  "xend", "yend", "region_id", "region_class",
  "metric", "x_var", "y_var"
))

#' Guard: abort with a helpful message if ggplot2 is not installed.
#'
#' Called at the top of every public plot method (plot.PPTree, plot.PPForest).
#' @noRd
check_ggplot2 <- function() {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop(
      "Package 'ggplot2' is required for plot methods. ",
      "Install it with install.packages('ggplot2').",
      call. = FALSE
    )
  }
}

# --- Design system ---
#
# Named constants for line weights, point sizes, alpha values, and
# structural colors used across all plot types.  These ensure a cohesive
# look and make it easy to adjust the overall visual style in one place.
#
# The design system has two layers:
#
#   1. Structural constants (below): fixed values for non-data elements
#      like edges, borders, thresholds, and decision boundaries.  These
#      use neutral greys to avoid competing with data-mapped colors.
#
#   2. Data-mapped colors: per-class fill and colour generated by
#      get_class_colors() using evenly-spaced HCL hues.  Applied via
#      scale_fill_manual / scale_color_manual so users can override
#      with + scale_fill_manual(values = ...).
#
# Node dimensions (pptree_node_w, etc.) must match the C++ LayoutParams
# defaults so that histogram bars and leaf labels align with the
# rectangles produced by compute_tree_layout().

# Line weights
pptree_lw_light  <- 0.4    # edges, node borders
pptree_lw_medium <- 0.6    # boundary lines, thresholds

# Point sizes
pptree_pt_small  <- 1.2    # pairwise facets
pptree_pt_medium <- 1.8    # 2D boundary

# Alpha values
pptree_alpha_region <- 0.25  # decision region fill
pptree_alpha_hist   <- 0.65  # histogram bars
pptree_alpha_leaf   <- 0.30  # leaf fill
pptree_alpha_proj   <- 0.60  # projection histogram

# Structural colors (not data-mapped)
pptree_col_edge      <- "grey55"
pptree_col_border    <- "grey50"
pptree_col_threshold <- "grey25"
pptree_col_boundary  <- "grey30"
pptree_col_tick      <- "grey40"
pptree_col_bar       <- "#5B8BA0"

# Node dimensions (must match C++ LayoutParams)
pptree_node_w <- 0.8; pptree_node_h <- 0.7
pptree_leaf_w <- 0.5; pptree_leaf_h <- 0.3

#' Shared ggplot2 theme for all non-structure plots.
#'
#' Uses \code{theme_minimal} as a base with slightly larger titles and no
#' minor gridlines.  The tree structure plot uses \code{theme_void()}
#' instead (no axes, no grid) since it renders on an abstract 2D canvas.
#' @noRd
pptree_theme <- function() {
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(
    plot.title       = ggplot2::element_text(size = ggplot2::rel(1.1)),
    panel.grid.minor = ggplot2::element_blank()
  )
}

# ======================================================================
# Shared helpers
# ======================================================================

#' Extract variable names from a model.
#'
#' Prefers column names from the training matrix (model$x).  Falls back
#' to "x1", "x2", ... if column names are absent.
#'
#' @param model A PPTree or PPForest model with \code{$x} and optionally
#'   \code{$vi}.
#' @return Character vector of length p (number of features).
#' @noRd
get_variable_names <- function(model) {
  p <- if (!is.null(model$vi$projections)) {
    length(model$vi$projections)
  } else {
    ncol(model$x)
  }

  if (!is.null(colnames(model$x))) {
    colnames(model$x)
  } else {
    paste0("x", seq_len(p))
  }
}

#' Generate a perceptually-uniform color palette for class labels.
#'
#' Colors are evenly spaced in HCL hue space (lightness = 65, chroma = 100)
#' to ensure maximal visual distinction between classes.  Named by the
#' class label so they can be passed directly to \code{scale_fill_manual()}.
#'
#' @param classes Character vector of unique class labels.
#' @return Named character vector of hex colours, one per class.
#' @noRd
get_class_colors <- function(classes) {
  n <- length(classes)
  hues <- seq(15, 375, length.out = n + 1)[seq_len(n)]
  colors <- grDevices::hcl(h = hues, l = 65, c = 100)
  names(colors) <- classes
  colors
}

#' Equalize two ranges so both span the same distance (for square plots).
#'
#' Both ranges are expanded symmetrically about their midpoints to match
#' the larger span.  Used before \code{coord_fixed(ratio = 1)} to ensure
#' the 2D boundary plot is square without distortion.
#'
#' @param x_range Numeric vector of length 2 (x_min, x_max).
#' @param y_range Numeric vector of length 2 (y_min, y_max).
#' @return List with elements \code{$x} and \code{$y}, each a length-2
#'   numeric vector.
#' @noRd
equalize_ranges <- function(x_range, y_range) {
  x_span <- diff(x_range)
  y_span <- diff(y_range)
  max_span <- max(x_span, y_span)
  x_mid <- mean(x_range)
  y_mid <- mean(y_range)
  list(
    x = c(x_mid - max_span / 2, x_mid + max_span / 2),
    y = c(y_mid - max_span / 2, y_mid + max_span / 2)
  )
}

# ======================================================================
# Tree structure plot
# ======================================================================

#' Compute histogram bar rectangles for one internal (condition) node.
#'
#' Bins the projected values by class, then maps bin coordinates from
#' projection space to the node's rectangle in the tree layout canvas.
#' This is NOT a standard ggplot2 \code{geom_histogram} — it produces raw
#' rectangle coordinates (xmin/xmax/ymin/ymax) that are drawn with
#' \code{geom_rect} so each node's histogram is embedded inside its box.
#'
#' @param nd A node data list from \code{pptree_tree_node_data()},
#'   with \code{$projected} (numeric), \code{$classes} (integer),
#'   and \code{$threshold} (numeric).
#' @param cx,cy Center position of the node on the layout canvas.
#' @param node_w,node_h Width and height of the node rectangle.
#' @param class_labels Character vector of class names (model$classes).
#' @param n_bins Number of histogram bins (default 15).
#' @return List with:
#'   \describe{
#'     \item{bars}{data.frame with xmin, xmax, ymin, ymax, class columns}
#'     \item{thr_x}{x-coordinate of the threshold line in canvas space}
#'     \item{thr_y_min, thr_y_max}{y-extent of the threshold line}
#'     \item{ticks}{data.frame with x, y, label for axis tick labels}
#'   }
#'   or NULL if no non-empty bins exist.
#' @noRd
compute_histogram_bars <- function(nd, cx, cy, node_w, node_h, class_labels, n_bins = 15) {
  vals <- nd$projected
  cls <- class_labels[nd$classes]
  threshold <- nd$threshold

  breaks <- seq(min(vals), max(vals), length.out = n_bins + 1)
  unique_classes <- unique(cls)

  bars <- list()
  for (cl in unique_classes) {
    cl_vals <- vals[cls == cl]
    h <- graphics::hist(cl_vals, breaks = breaks, plot = FALSE)
    if (any(h$counts > 0)) {
      bars[[length(bars) + 1L]] <- data.frame(
        bin_left  = h$breaks[-length(h$breaks)],
        bin_right = h$breaks[-1],
        count     = h$counts,
        class     = cl,
        stringsAsFactors = FALSE
      )
    }
  }

  if (length(bars) == 0) return(NULL)

  bar_df <- do.call(rbind, bars)
  bar_df <- bar_df[bar_df$count > 0, , drop = FALSE]

  if (nrow(bar_df) == 0) return(NULL)

  # Map projected-value-space to node coordinate space
  val_min <- min(breaks)
  val_max <- max(breaks)
  val_range <- val_max - val_min
  if (val_range == 0) val_range <- 1

  margin <- 0.05
  draw_w <- node_w * (1 - 2 * margin)
  draw_h <- node_h * (1 - 2 * margin)

  max_count <- max(bar_df$count)

  bar_df$xmin <- cx - node_w / 2 + node_w * margin + (bar_df$bin_left - val_min) / val_range * draw_w
  bar_df$xmax <- cx - node_w / 2 + node_w * margin + (bar_df$bin_right - val_min) / val_range * draw_w
  bar_df$ymin <- cy - node_h / 2 + node_h * margin
  bar_df$ymax <- bar_df$ymin + bar_df$count / max_count * draw_h

  # Threshold line in data coordinates
  thr_x <- cx - node_w / 2 + node_w * margin + (threshold - val_min) / val_range * draw_w

  # Axis tick data
  tick_y <- cy - node_h / 2
  tick_labels <- data.frame(
    x = c(cx - node_w / 2 + node_w * margin, cx + node_w / 2 - node_w * margin),
    y = tick_y,
    label = formatC(c(val_min, val_max), format = "g", digits = 3),
    stringsAsFactors = FALSE
  )

  list(bars = bar_df, thr_x = thr_x, thr_y_min = cy - node_h / 2 + node_h * margin, thr_y_max = cy + node_h / 2 - node_h * margin, ticks = tick_labels)
}

#' Render the tree structure as a ggplot2 plot.
#'
#' Draws a tree diagram on a 2D canvas with:
#' \itemize{
#'   \item Edges connecting parent to child nodes (grey segments with labels)
#'   \item Internal nodes as white rectangles containing stacked class
#'     histograms of the projected values at that split, with a dashed
#'     threshold line
#'   \item Leaf nodes as class-colored rectangles with the predicted class
#'     label
#' }
#'
#' Layout positions come from the C++ \code{compute_tree_layout()} (pre-order,
#' left-aligned).  Per-node projection data comes from
#' \code{pptree_tree_node_data()} which routes all training observations
#' through the tree.
#'
#' @param model A PPTree model with \code{$root}, \code{$x}, \code{$y},
#'   \code{$classes}.
#' @param ... Currently unused.
#' @return A ggplot2 object (theme_void, no axes).
#' @noRd
plot_tree_structure <- function(model, ...) {
  nodes <- pptree_tree_node_data(model, model$x, model$y)
  class_labels <- model$classes
  class_colors <- get_class_colors(class_labels)

  node_w <- pptree_node_w
  node_h <- pptree_node_h
  leaf_w <- pptree_leaf_w
  leaf_h <- pptree_leaf_h

  layout <- pptree_tree_layout(model)
  node_df <- layout$nodes
  # C++ uses 0-indexed node_idx, convert to 1-indexed for R
  node_df$node_idx <- node_df$node_idx + 1L
  edge_df <- layout$edges

  # Collect all histogram bars, threshold lines, and axis ticks
  all_bars <- list()
  all_thr_segs <- list()
  all_ticks <- list()
  node_bg_df <- list()
  leaf_bg_df <- list()
  leaf_label_df <- list()

  for (i in seq_len(nrow(node_df))) {
    row <- node_df[i, ]
    nd <- nodes[[row$node_idx]]

    if (nd$is_leaf) {
      predicted <- class_labels[nd$value]
      leaf_bg_df[[length(leaf_bg_df) + 1L]] <- data.frame(
        xmin = row$x - leaf_w / 2, xmax = row$x + leaf_w / 2,
        ymin = row$y - leaf_h / 2, ymax = row$y + leaf_h / 2,
        class = predicted,
        stringsAsFactors = FALSE
      )
      leaf_label_df[[length(leaf_label_df) + 1L]] <- data.frame(
        x = row$x, y = row$y, label = predicted,
        stringsAsFactors = FALSE
      )
    } else {
      node_bg_df[[length(node_bg_df) + 1L]] <- data.frame(
        xmin = row$x - node_w / 2, xmax = row$x + node_w / 2,
        ymin = row$y - node_h / 2, ymax = row$y + node_h / 2,
        stringsAsFactors = FALSE
      )

      hist_data <- compute_histogram_bars(nd, row$x, row$y, node_w, node_h, class_labels)
      
      if (!is.null(hist_data)) {
        all_bars[[length(all_bars) + 1L]] <- hist_data$bars
        all_thr_segs[[length(all_thr_segs) + 1L]] <- data.frame(
          x = hist_data$thr_x, xend = hist_data$thr_x,
          y = hist_data$thr_y_min, yend = hist_data$thr_y_max,
          stringsAsFactors = FALSE
        )
        all_ticks[[length(all_ticks) + 1L]] <- hist_data$ticks
      }
    }
  }

  bar_df <- if (length(all_bars) > 0) do.call(rbind, all_bars) else NULL
  thr_df <- if (length(all_thr_segs) > 0) do.call(rbind, all_thr_segs) else NULL
  tick_df <- if (length(all_ticks) > 0) do.call(rbind, all_ticks) else NULL
  node_bg <- if (length(node_bg_df) > 0) do.call(rbind, node_bg_df) else NULL
  leaf_bg <- if (length(leaf_bg_df) > 0) do.call(rbind, leaf_bg_df) else NULL
  leaf_labels <- if (length(leaf_label_df) > 0) do.call(rbind, leaf_label_df) else NULL

  p <- ggplot2::ggplot() +
    ggplot2::theme_void()

  # Edges
  if (nrow(edge_df) > 0) {
    p <- p + ggplot2::geom_segment(
      data = edge_df,
      ggplot2::aes(x = from_x, y = from_y, xend = to_x, yend = to_y),
      color = pptree_col_edge, linewidth = pptree_lw_light
    )
    # Edge labels at midpoint
    edge_label_df <- data.frame(
      x = (edge_df$from_x + edge_df$to_x) / 2,
      y = (edge_df$from_y + edge_df$to_y) / 2,
      label = edge_df$edge_label,
      stringsAsFactors = FALSE
    )
    p <- p + ggplot2::geom_label(
      data = edge_label_df,
      ggplot2::aes(x = x, y = y, label = label),
      size = 2.5, label.size = 0, fill = "white", alpha = 0.8,
      label.padding = ggplot2::unit(0.15, "lines")
    )
  }

  # Node backgrounds
  if (!is.null(node_bg)) {
    p <- p + ggplot2::geom_rect(
      data = node_bg,
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      fill = "white", color = pptree_col_border, linewidth = pptree_lw_light
    )
  }

  # Histogram bars
  if (!is.null(bar_df)) {
    p <- p + ggplot2::geom_rect(
      data = bar_df,
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax,
                   fill = class),
      alpha = pptree_alpha_hist, color = NA
    )
  }

  # Threshold lines
  if (!is.null(thr_df)) {
    p <- p + ggplot2::geom_segment(
      data = thr_df,
      ggplot2::aes(x = x, y = y, xend = xend, yend = yend),
      linetype = "dashed", color = pptree_col_threshold, linewidth = pptree_lw_medium
    )
  }

  # Axis ticks
  if (!is.null(tick_df)) {
    p <- p + ggplot2::geom_text(
      data = tick_df,
      ggplot2::aes(x = x, y = y, label = label),
      size = 1.8, vjust = 1.5, color = pptree_col_tick
    )
  }

  # Leaf backgrounds
  if (!is.null(leaf_bg)) {
    p <- p + ggplot2::geom_rect(
      data = leaf_bg,
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax,
                   fill = class),
      alpha = pptree_alpha_leaf, color = pptree_col_border, linewidth = pptree_lw_light
    )
  }

  # Leaf labels
  if (!is.null(leaf_labels)) {
    p <- p + ggplot2::geom_text(
      data = leaf_labels,
      ggplot2::aes(x = x, y = y, label = label),
      size = 3, fontface = "bold"
    )
  }

  # Color scale and title
  p <- p +
    ggplot2::scale_fill_manual(values = class_colors, name = "Class") +
    ggplot2::ggtitle("PPTree Structure") +
    ggplot2::coord_cartesian(
      xlim = c(min(node_df$x) - node_w / 2 - 0.2,
               max(node_df$x) + node_w / 2 + 0.2),
      ylim = c(min(node_df$y) - node_h / 2 - 0.2,
               max(node_df$y) + node_h / 2 + 0.2)
    )

  p
}

# ======================================================================
# Variable importance plot
# ======================================================================

#' Display labels for each variable importance metric.
#'
#' Keys must match names in \code{model$vi} (set during training/forest
#' construction).
#' @noRd
metric_labels <- c(
  projections = "Projection",
  weighted    = "Weighted",
  permuted    = "Permuted"
)

#' Render a horizontal bar chart of variable importance.
#'
#' Supports multiple importance metrics (projection, weighted, permuted).
#' When a single metric is available, bars use the neutral
#' \code{pptree_col_bar} colour.  With multiple metrics, bars are
#' colour-coded and dodged.  Variables are ordered by the first
#' available metric's values.
#'
#' @param model A PPTree or PPForest model with \code{$vi} (list of named
#'   numeric vectors) and \code{$x} (for variable names).
#' @param ... Currently unused.
#' @return A ggplot2 object.
#' @noRd
plot_importance <- function(model, ...) {
  vnames <- get_variable_names(model)
  available <- intersect(names(metric_labels), names(model$vi))

  dfs <- list()
  for (m in available) {
    values <- model$vi[[m]]
    dfs[[m]] <- data.frame(
      variable   = vnames,
      importance = values,
      metric     = unname(metric_labels[m]),
      stringsAsFactors = FALSE
    )
  }

  df <- do.call(rbind, dfs)

  # Order variables by first metric's values
  first_values <- model$vi[[available[1]]]
  df$variable <- factor(df$variable, levels = vnames[order(first_values)])
  df$metric <- factor(df$metric, levels = unname(metric_labels[available]))

  if (length(available) > 1) {
    p <- ggplot2::ggplot(df, ggplot2::aes(x = importance, y = variable, fill = metric)) +
      ggplot2::geom_col(position = "dodge") +
      ggplot2::labs(
        title = "Variable Importance",
        x     = "Importance",
        y     = NULL,
        fill  = "Metric"
      ) +
      pptree_theme() +
      ggplot2::theme(panel.grid.major.y = ggplot2::element_blank())
  } else {
    p <- ggplot2::ggplot(df, ggplot2::aes(x = importance, y = variable)) +
      ggplot2::geom_col(fill = pptree_col_bar) +
      ggplot2::labs(
        title = "Variable Importance",
        x     = "Importance",
        y     = NULL
      ) +
      pptree_theme() +
      ggplot2::theme(panel.grid.major.y = ggplot2::element_blank())
  }

  p
}

# ======================================================================
# Projection histogram plot
# ======================================================================

#' Retrieve a tree node by breadth-first (BFS) index.
#'
#' Traverses the tree in BFS order and returns the node at position
#' \code{index} (1-based).  Used to locate the target node for projection
#' plots when the user specifies a node number.
#'
#' @param root The root node of the tree (\code{$root} from a PPTree model).
#' @param index 1-based BFS index (1 = root, 2 = first child, etc.).
#' @return The tree node at the specified BFS position.
#' @note Stops with an error if the index is out of range.
#' @noRd
get_node_bfs <- function(root, index) {
  queue <- list(root)
  i <- 0L

  while (length(queue) > 0) {
    current <- queue[[1]]
    queue <- queue[-1]
    i <- i + 1L

    if (i == index) return(current)

    if (!is.null(current$lower)) queue <- c(queue, list(current$lower))
    if (!is.null(current$upper)) queue <- c(queue, list(current$upper))
  }

  stop("Node index ", index, " is out of range.", call. = FALSE)
}

#' Render a projection histogram at a specified split node.
#'
#' Projects all training observations onto the node's projector vector,
#' draws overlapping histograms coloured by class, and marks the split
#' threshold with a dashed vertical line.  This shows how well the
#' node's projection separates the classes.
#'
#' @param model A PPTree model with \code{$root}, \code{$x}, \code{$y},
#'   \code{$classes}.
#' @param node 1-based BFS index of the target node (default: root).
#' @param ... Currently unused.
#' @return A ggplot2 object.
#' @note Stops with an error if the specified node is a leaf.
#' @noRd
plot_projection <- function(model, node = 1L, ...) {
  target_node <- get_node_bfs(model$root, node)

  if (!is.null(target_node$value)) {
    stop("Node ", node, " is a leaf node and has no projector.", call. = FALSE)
  }

  projector <- target_node$projector
  projected <- as.numeric(model$x %*% projector)
  class_labels <- model$classes[model$y]

  df <- data.frame(
    projected = projected,
    class     = class_labels,
    stringsAsFactors = FALSE
  )

  threshold <- target_node$threshold

  ggplot2::ggplot(df, ggplot2::aes(x = projected, fill = class)) +
    ggplot2::geom_histogram(
      bins     = 30,
      alpha    = pptree_alpha_proj,
      position = "identity"
    ) +
    ggplot2::geom_vline(
      xintercept = threshold,
      linetype   = "dashed",
      color      = pptree_col_threshold,
      linewidth  = pptree_lw_medium
    ) +
    ggplot2::labs(
      title = paste0("Projected Data at Node ", node),
      x     = "Projected Value",
      y     = "Count",
      fill  = "Class"
    ) +
    pptree_theme()
}

# ======================================================================
# Decision boundary plots
# ======================================================================

#' Dispatch to the appropriate boundary plot based on feature count.
#'
#' Selects the visualization strategy based on the number of features (p):
#' \describe{
#'   \item{p = 1}{1D number-line plot.  Background rectangles show decision
#'     regions; solid vertical lines mark boundaries; jittered points show
#'     the data.}
#'   \item{p = 2}{Single 2D scatterplot.  Convex region polygons (from C++
#'     Sutherland-Hodgman clipping) fill the background; boundary line
#'     segments are drawn on top; data points are overlaid.  Uses
#'     \code{coord_fixed(ratio = 1)} for undistorted angles.}
#'   \item{p >= 3}{Pairwise scatterplot matrix (lower triangle).  Each panel
#'     shows a 2D projection with non-displayed variables held at their
#'     medians.  \code{facet_grid} with free scales and zero expansion
#'     ensures full region coverage per panel.}
#' }
#'
#' @param model A PPTree model with \code{$root}, \code{$x}, \code{$y},
#'   \code{$classes}.
#' @param ... Passed through to the specific boundary plot function.
#' @return A ggplot2 object.
#' @noRd
plot_boundaries <- function(model, ...) {
  p <- ncol(model$x)

  if (p == 1L) {
    plot_boundaries_1d(model)
  } else if (p == 2L) {
    plot_boundaries_2d(model, ...)
  } else {
    plot_boundaries_pairwise(model, ...)
  }
}

#' Convert C++ region polygon data to a ggplot2-ready data frame.
#'
#' Transforms the list-of-lists output from \code{pptree_decision_regions()}
#' (C++ RegionVisitor) into a flat data frame suitable for
#' \code{ggplot2::geom_polygon()}.  Each polygon becomes a group of rows
#' sharing a unique region_id, with vertices in the order produced by the
#' Sutherland-Hodgman algorithm (consistent winding for correct polygon
#' rendering).
#'
#' Class indices from C++ are 1-based (matching R's convention for the
#' response vector) and are mapped to human-readable labels via the
#' model's class vector.
#'
#' @param regions List of region lists, each with \code{$x}, \code{$y}
#'   (numeric vectors of vertex coordinates) and \code{$class} (integer
#'   class index, 1-based from C++).
#' @param class_labels Character vector of class names (model$classes).
#' @return Data frame with columns x, y, region_id, region_class, or
#'   NULL if no valid polygons exist.  Degenerate regions with fewer
#'   than 3 vertices are silently dropped.
#' @noRd
build_region_df <- function(regions, class_labels) {
  if (length(regions) == 0) return(NULL)

  dfs <- list()
  for (i in seq_along(regions)) {
    r <- regions[[i]]
    if (length(r$x) >= 3) {
      dfs[[length(dfs) + 1L]] <- data.frame(
        x = r$x, y = r$y,
        region_id = i,
        region_class = class_labels[r$class],
        stringsAsFactors = FALSE
      )
    }
  }

  if (length(dfs) == 0) return(NULL)
  do.call(rbind, dfs)
}

#' Render decision boundaries for a 1-feature model.
#'
#' Draws a number-line plot with three layers (back to front):
#' \enumerate{
#'   \item Coloured background rectangles for each decision region
#'     (predicted class determined by running \code{pptree_predict} on each
#'     region's midpoint)
#'   \item Jittered data points coloured by true class (y is meaningless,
#'     jittered around 0 for visual separation)
#'   \item Solid vertical lines at each split's decision boundary
#' }
#'
#' Boundary positions are computed as \code{threshold / projector[1]} for
#' each internal node.  For a 1D projector \code{a = [a1]}, the split
#' condition \code{a^T x < t} becomes \code{a1 * x < t}, i.e.
#' \code{x < t/a1}.  The sorted boundary positions partition the x-axis
#' into contiguous regions, each assigned the class predicted by the tree
#' for that region's midpoint.
#'
#' The y-axis is suppressed (no title, no ticks, no labels) since the
#' vertical dimension has no meaning — it exists only to spread out the
#' jittered points for readability.
#'
#' @param model A PPTree model with 1 feature column in \code{$x}.
#' @return A ggplot2 object (no y-axis).
#' @noRd
plot_boundaries_1d <- function(model) {
  vnames <- get_variable_names(model)
  all_class_labels <- model$classes
  class_colors <- get_class_colors(all_class_labels)
  obs_class_labels <- all_class_labels[model$y]

  nodes <- pptree_tree_node_data(model, model$x, model$y)

  boundary_x <- vapply(
    Filter(function(nd) !nd$is_leaf, nodes),
    function(nd) nd$threshold / nd$projector[1],
    numeric(1)
  )
  boundary_x <- sort(boundary_x)

  x_range <- range(model$x[, 1])
  x_pad <- diff(x_range) * 0.05
  x_range <- x_range + c(-x_pad, x_pad)

  # Build region rectangles from sorted boundaries
  # Predict the class for the midpoint of each region
  edges <- c(x_range[1], boundary_x, x_range[2])
  region_rects <- list()
  for (r in seq_len(length(edges) - 1)) {
    mid <- (edges[r] + edges[r + 1]) / 2
    mid_vec <- matrix(mid, nrow = 1)
    pred_class <- all_class_labels[pptree_predict(model, mid_vec)]
    region_rects[[r]] <- data.frame(
      xmin = edges[r], xmax = edges[r + 1],
      region_class = pred_class,
      stringsAsFactors = FALSE
    )
  }
  region_df <- do.call(rbind, region_rects)

  obs_data <- data.frame(
    x     = model$x[, 1],
    class = obs_class_labels,
    stringsAsFactors = FALSE
  )

  # Make the plot square: y-range equals x-range width, centred at 0
  x_span <- diff(x_range)
  y_range <- c(-x_span / 2, x_span / 2)

  ggplot2::ggplot() +
    ggplot2::geom_rect(
      data = region_df,
      ggplot2::aes(xmin = xmin, xmax = xmax, ymin = y_range[1], ymax = y_range[2],
                   fill = region_class),
      alpha = pptree_alpha_region
    ) +
    ggplot2::geom_jitter(
      data   = obs_data,
      ggplot2::aes(x = x, y = 0, color = class),
      height = 0.3, size = pptree_pt_medium
    ) +
    ggplot2::geom_vline(
      xintercept = boundary_x,
      linetype   = "solid",
      color      = pptree_col_boundary,
      linewidth  = pptree_lw_medium
    ) +
    ggplot2::scale_fill_manual(values = class_colors, name = "Class") +
    ggplot2::scale_color_manual(values = class_colors, name = "Class") +
    ggplot2::scale_x_continuous(expand = ggplot2::expansion(0)) +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(0)) +
    ggplot2::labs(
      title = "Decision Boundaries",
      x     = vnames[1]
    ) +
    ggplot2::coord_cartesian(xlim = x_range, ylim = y_range) +
    pptree_theme() +
    ggplot2::theme(
      aspect.ratio = 1,
      axis.title.y = ggplot2::element_blank(),
      axis.text.y  = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank()
    )
}

#' Render decision boundaries for a 2-feature model.
#'
#' Draws a single scatterplot with:
#' \itemize{
#'   \item Convex region polygons (Sutherland-Hodgman clipped) coloured by
#'     predicted class, computed by \code{pptree_decision_regions()} in C++
#'   \item Boundary line segments (parametric-clipped) from
#'     \code{pptree_boundary_segments()} in C++
#'   \item Data points coloured by true class
#' }
#'
#' The plot uses \code{coord_fixed(ratio = 1)} with equalized ranges so
#' the decision boundaries appear at their true angles.  Region polygons
#' are computed on an extended bounding box (0.5x padding) so they reach
#' the plot edges.
#'
#' @param model A PPTree model with 2 feature columns in \code{$x}.
#' @param ... Passed to \code{geom_segment} (e.g. additional aesthetics).
#' @return A ggplot2 object.
#' @noRd
plot_boundaries_2d <- function(model, ...) {
  vnames <- get_variable_names(model)
  class_labels <- model$classes
  class_colors <- get_class_colors(class_labels)

  obs_class_labels <- class_labels[model$y]

  x_range <- range(model$x[, 1])
  y_range <- range(model$x[, 2])
  x_pad <- diff(x_range) * 0.05
  y_pad <- diff(y_range) * 0.05
  x_range <- x_range + c(-x_pad, x_pad)
  y_range <- y_range + c(-y_pad, y_pad)

  # Equalize ranges so the plot is square with coord_fixed
  eq <- equalize_ranges(x_range, y_range)
  x_range <- eq$x
  y_range <- eq$y

  # Use a larger bounding box for regions so they extend to the plot edges
  x_ext <- diff(x_range) * 0.5
  y_ext <- diff(y_range) * 0.5
  region_bbox <- c(x_range[1] - x_ext, x_range[2] + x_ext,
                   y_range[1] - y_ext, y_range[2] + y_ext)

  # Decision regions (computed over extended bbox, clipped visually by coord)
  regions <- pptree_decision_regions(
    model, c(0L, 1L), numeric(0),
    region_bbox[1], region_bbox[2], region_bbox[3], region_bbox[4]
  )
  region_df <- build_region_df(regions, class_labels)

  # Boundary segments
  segments <- pptree_boundary_segments(
    model, c(0L, 1L), numeric(0),
    region_bbox[1], region_bbox[2], region_bbox[3], region_bbox[4]
  )

  obs_data <- data.frame(
    x     = model$x[, 1],
    y     = model$x[, 2],
    class = obs_class_labels,
    stringsAsFactors = FALSE
  )

  p <- ggplot2::ggplot()

  # Regions
  if (!is.null(region_df)) {
    p <- p + ggplot2::geom_polygon(
      data = region_df,
      ggplot2::aes(x = x, y = y, group = region_id, fill = region_class),
      alpha = pptree_alpha_region
    )
  }

  # Boundary lines
  if (nrow(segments) > 0) {
    p <- p + ggplot2::geom_segment(
      data = segments,
      ggplot2::aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
      linewidth = pptree_lw_medium, color = pptree_col_boundary, ...
    )
  }

  # Data points
  p <- p + ggplot2::geom_point(
    data = obs_data,
    ggplot2::aes(x = x, y = y, color = class),
    size = pptree_pt_medium
  )

  p +
    ggplot2::scale_fill_manual(values = class_colors, name = "Class") +
    ggplot2::scale_color_manual(values = class_colors, name = "Class") +
    ggplot2::labs(
      title = "Decision Boundaries",
      x     = vnames[1],
      y     = vnames[2]
    ) +
    ggplot2::coord_fixed(ratio = 1, xlim = x_range, ylim = y_range) +
    pptree_theme()
}

#' Render pairwise decision boundaries for a model with 3+ features.
#'
#' Creates a lower-triangular scatterplot matrix using \code{facet_grid()}.
#' For each pair of features (i, j), all other features are held at
#' their median values and the tree's decision regions and boundary
#' lines are projected onto the (i, j) plane.
#'
#' Layout uses \code{facet_grid(y_var ~ x_var, switch = "both")} so that
#' column strips appear at the bottom (serving as x-axis labels) and
#' row strips appear on the left (serving as y-axis labels), similar
#' to a \code{pairs()} plot.  All panels use free scales and
#' \code{aspect.ratio = 1}.
#'
#' @section Full region coverage:
#' The region bounding box is set to exactly the padded data range
#' (data range +/- 5\%).  Scale expansion is disabled via
#' \code{expansion(0)}, so the visible coordinate range equals the
#' polygon bounding box.  Since the Sutherland-Hodgman algorithm
#' partitions the entire bbox across all leaves, the region polygons
#' tile the panel completely with no whitespace gaps.
#'
#' @section Axis labels:
#' The overall x/y axis titles are suppressed.  The strip labels
#' (placed at the axis positions via \code{switch = "both"}) serve as
#' the axis labels, showing the variable name for each row and column.
#'
#' Remove empty upper-triangle panels from a pairwise facet_grid plot.
#'
#' Converts a ggplot with \code{facet_grid(y_var ~ x_var)} to a gtable
#' and replaces panel grobs in the upper triangle (where the column
#' index exceeds the row index) with \code{nullGrob()}.  This prevents
#' empty panels from showing grid lines and background.
#'
#' @param p A ggplot object produced by the pairwise boundary builder.
#' @return A gtable with upper-triangle panel grobs blanked out.
#' @noRd
strip_upper_triangle <- function(p) {
  g <- ggplot2::ggplotGrob(p)

  panels <- g$layout[grepl("^panel", g$layout$name), ]
  panel_rows <- sort(unique(panels$t))
  panel_cols <- sort(unique(panels$l))

  for (i in seq_len(nrow(panels))) {
    facet_row <- match(panels$t[i], panel_rows)
    facet_col <- match(panels$l[i], panel_cols)

    if (facet_col > facet_row) {
      g$grobs[[which(g$layout$name == panels$name[i])]] <- grid::nullGrob()
    }
  }

  g
}

#' @param model A PPTree model with 3+ feature columns in \code{$x}.
#' @param ... Passed to \code{geom_segment} (e.g. additional aesthetics).
#' @return A gtable with empty upper-triangle panels removed.
#' @noRd
plot_boundaries_pairwise <- function(model, ...) {
  vnames <- get_variable_names(model)
  class_labels <- model$classes
  class_colors <- get_class_colors(class_labels)
  n_vars <- ncol(model$x)

  obs_class_labels <- class_labels[model$y]
  medians <- apply(model$x, 2, stats::median)

  # Generate all pairwise combinations (lower triangle of scatterplot matrix)
  pairs <- utils::combn(n_vars, 2, simplify = FALSE)

  # Factor levels for grid layout: x_var = vars 1..(p-1), y_var = vars 2..p
  x_var_levels <- vnames[seq_len(n_vars - 1L)]
  y_var_levels <- vnames[seq(2L, n_vars)]

  all_segments <- list()
  all_regions <- list()
  all_obs <- list()

  for (k in seq_along(pairs)) {
    i <- pairs[[k]][1]
    j <- pairs[[k]][2]
    other <- setdiff(seq_len(n_vars), c(i, j))

    x_range <- range(model$x[, i])
    y_range <- range(model$x[, j])
    x_pad <- diff(x_range) * 0.05
    y_pad <- diff(y_range) * 0.05
    x_range <- x_range + c(-x_pad, x_pad)
    y_range <- y_range + c(-y_pad, y_pad)

    # Region bbox matches the padded data range exactly.  Combined with
    # scale expansion(0) below, this ensures region polygons tile each
    # panel completely: the polygon vertices define the scale limits, and
    # zero expansion prevents ggplot2 from adding extra whitespace beyond
    # the polygon edges.
    region_bbox <- c(x_range[1], x_range[2], y_range[1], y_range[2])

    # Decision regions (extended bbox, clipped visually by facet coord)
    regs <- pptree_decision_regions(
      model, c(i - 1L, j - 1L), medians[other],
      region_bbox[1], region_bbox[2], region_bbox[3], region_bbox[4]
    )
    reg_df <- build_region_df(regs, class_labels)
    if (!is.null(reg_df)) {
      # Offset region_id to be unique across panels
      offset <- if (length(all_regions) > 0) {
        max(do.call(rbind, all_regions)$region_id)
      } else {
        0
      }
      reg_df$region_id <- reg_df$region_id + offset
      reg_df$x_var <- factor(vnames[i], levels = x_var_levels)
      reg_df$y_var <- factor(vnames[j], levels = y_var_levels)
      all_regions[[k]] <- reg_df
    }

    # Boundary segments (also extended)
    segs <- pptree_boundary_segments(
      model, c(i - 1L, j - 1L), medians[other],
      region_bbox[1], region_bbox[2], region_bbox[3], region_bbox[4]
    )

    if (nrow(segs) > 0) {
      segs$x_var <- factor(vnames[i], levels = x_var_levels)
      segs$y_var <- factor(vnames[j], levels = y_var_levels)
      all_segments[[k]] <- segs
    }

    all_obs[[k]] <- data.frame(
      x     = model$x[, i],
      y     = model$x[, j],
      class = obs_class_labels,
      x_var = factor(vnames[i], levels = x_var_levels),
      y_var = factor(vnames[j], levels = y_var_levels),
      stringsAsFactors = FALSE
    )
  }

  obs_data <- do.call(rbind, all_obs)
  seg_data <- do.call(rbind, Filter(Negate(is.null), all_segments))
  reg_data <- do.call(rbind, Filter(Negate(is.null), all_regions))

  p <- ggplot2::ggplot()

  # Regions
  if (!is.null(reg_data) && nrow(reg_data) > 0) {
    p <- p + ggplot2::geom_polygon(
      data = reg_data,
      ggplot2::aes(x = x, y = y, group = region_id, fill = region_class),
      alpha = pptree_alpha_region
    )
  }

  # Boundary lines
  if (!is.null(seg_data) && nrow(seg_data) > 0) {
    p <- p + ggplot2::geom_segment(
      data = seg_data,
      ggplot2::aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
      linewidth = pptree_lw_medium, color = pptree_col_boundary, ...
    )
  }

  # Data points
  p <- p + ggplot2::geom_point(
    data = obs_data,
    ggplot2::aes(x = x, y = y, color = class),
    size = pptree_pt_small
  )

  p <- p +
    ggplot2::facet_grid(y_var ~ x_var, scales = "free", switch = "both") +
    ggplot2::scale_fill_manual(values = class_colors, name = "Class") +
    ggplot2::scale_color_manual(values = class_colors, name = "Class") +
    ggplot2::scale_x_continuous(expand = ggplot2::expansion(0)) +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(0)) +
    ggplot2::labs(title = "Decision Boundaries") +
    pptree_theme() +
    ggplot2::theme(
      aspect.ratio     = 1,
      strip.placement  = "outside",
      axis.title       = ggplot2::element_blank()
    )

  strip_upper_triangle(p)
}

# ======================================================================
# Mosaic layout
# ======================================================================

#' Render a composite mosaic of tree structure, importance, and boundaries.
#'
#' Arranges three plots in a 2-column grid layout using the grid package:
#' \itemize{
#'   \item Left column (full height): tree structure diagram
#'   \item Top-right: variable importance bar chart
#'   \item Bottom-right: decision boundaries
#' }
#'
#' Layout proportions adapt to the data:
#' \itemize{
#'   \item Column widths are computed from the tree's x-span (wider trees
#'     get a wider left column, clamped to 35--60\% of total width)
#'   \item Row heights adapt to the number of features: fewer features give
#'     more vertical space to importance, more features give more space to
#'     the pairwise boundary grid
#' }
#'
#' @param model A PPTree model.
#' @param ... Passed through to \code{plot_boundaries()}.
#' @return NULL (invisibly). The plot is drawn as a side effect via grid.
#' @noRd
plot_mosaic <- function(model, ...) {
  p_structure <- plot_tree_structure(model) +
    ggplot2::theme(plot.margin = ggplot2::margin(5, 10, 5, 5))
  p_importance <- plot_importance(model) +
    ggplot2::theme(plot.margin = ggplot2::margin(5, 5, 5, 10))
  p_boundaries <- plot_boundaries(model, ...)
  if (inherits(p_boundaries, "ggplot")) {
    p_boundaries <- p_boundaries +
      ggplot2::theme(plot.margin = ggplot2::margin(5, 5, 5, 10))
  }

  # Compute adaptive layout proportions from the data
  layout <- pptree_tree_layout(model)
  node_df <- layout$nodes
  tree_x_span <- diff(range(node_df$x)) + pptree_node_w + 0.4
  tree_frac <- max(0.35, min(0.60, tree_x_span / (tree_x_span + 3.0)))

  n_features <- ncol(model$x)
  imp_ratio <- if (n_features <= 2) 2 else if (n_features <= 4) 1 else 1
  bnd_ratio <- if (n_features <= 2) 1.5 else if (n_features <= 4) 2 else 3

  grid::grid.newpage()

  # Left column: structure (full height)
  # Right column: importance (top) + boundaries (bottom)
  grid::pushViewport(grid::viewport(
    layout = grid::grid.layout(2, 2,
      widths  = grid::unit(c(tree_frac, 1 - tree_frac), "null"),
      heights = grid::unit(c(imp_ratio, bnd_ratio), "null"))
  ))

  grid::pushViewport(grid::viewport(layout.pos.row = 1:2, layout.pos.col = 1))
  print(p_structure, newpage = FALSE)
  grid::popViewport()

  grid::pushViewport(grid::viewport(layout.pos.row = 1, layout.pos.col = 2))
  print(p_importance, newpage = FALSE)
  grid::popViewport()

  grid::pushViewport(grid::viewport(layout.pos.row = 2, layout.pos.col = 2))
  if (inherits(p_boundaries, "gtable")) {
    grid::grid.draw(p_boundaries)
  } else {
    print(p_boundaries, newpage = FALSE)
  }
  grid::popViewport()

  grid::popViewport()

  invisible(NULL)
}

# ======================================================================
# S3 plot methods
# ======================================================================

#' Plot a PPTree model.
#'
#' Visualizes a PPTree model. By default, shows a mosaic overview with tree
#' structure, decision boundaries, and variable importance. Use \code{type}
#' to show individual plots.
#'
#' @param x A PPTree model.
#' @param type Character string specifying the plot type. \code{NULL} (default)
#'   shows a mosaic overview. Other options: \code{"structure"} for tree with
#'   embedded histograms, \code{"importance"} for variable importance (all
#'   available metrics), \code{"projection"} for projected data at a node,
#'   \code{"boundaries"} for decision boundaries in feature space.
#' @param node Integer index of the node for projection plots (1-based, breadth-first
#'   order). Defaults to 1 (root node). Only used when \code{type = "projection"}.
#' @param ... Additional arguments passed to the internal plotting function.
#' @return A ggplot2 object (invisibly), or \code{NULL} for the mosaic layout.
#' @examples
#' \dontrun{
#' model <- PPTree(Type ~ ., data = iris)
#' plot(model)                         # mosaic overview
#' plot(model, type = "structure")     # tree structure only
#' plot(model, type = "importance")    # variable importance
#' plot(model, type = "projection")   # projection histogram
#' plot(model, type = "boundaries")   # decision boundaries
#' }
#' @export
plot.PPTree <- function(x, type = NULL, node = 1L, ...) {
  check_ggplot2()

  if (is.null(type)) {
    return(plot_mosaic(x, ...))
  }

  type <- match.arg(type, c("structure", "importance", "projection", "boundaries"))

  p <- switch(type,
    structure  = plot_tree_structure(x, ...),
    importance = plot_importance(x, ...),
    projection = plot_projection(x, node = node, ...),
    boundaries = plot_boundaries(x, ...)
  )

  if (inherits(p, "gtable")) {
    grid::grid.newpage()
    grid::grid.draw(p)
  } else {
    print(p)
  }
  invisible(p)
}

#' Plot a PPForest model.
#'
#' Visualizes a PPForest model. By default, shows variable importance across
#' all available metrics. Use \code{type} to show individual plots.
#'
#' @param x A PPForest model.
#' @param type Character string specifying the plot type.
#'   \code{"importance"} (default) shows variable importance (all available
#'   metrics), \code{"structure"} shows a specific tree with embedded histograms,
#'   \code{"projection"} shows projected data at a node,
#'   \code{"boundaries"} shows decision boundaries of a specific tree.
#' @param tree_index Integer index of the tree to plot (1-based). Only used when
#'   \code{type = "structure"}, \code{type = "projection"}, or
#'   \code{type = "boundaries"}. Defaults to 1.
#' @param node Integer index of the node for projection plots. Defaults to 1 (root).
#'   Only used when \code{type = "projection"}.
#' @param ... Additional arguments passed to the internal plotting function.
#' @return A ggplot2 object (invisibly).
#' @examples
#' \dontrun{
#' forest <- PPForest(Type ~ ., data = iris, size = 10)
#' plot(forest)
#' plot(forest, type = "structure", tree_index = 1)
#' plot(forest, type = "projection", tree_index = 1)
#' }
#' @export
plot.PPForest <- function(x, type = "importance",
                          tree_index = 1L, node = 1L, ...) {
  check_ggplot2()
  type <- match.arg(type, c("importance", "structure", "projection", "boundaries"))

  if (type %in% c("structure", "projection", "boundaries")) {
    tree <- x$trees[[tree_index]]
    tree$x <- x$x
    tree$y <- x$y
    tree$classes <- x$classes
  }

  p <- switch(type,
    importance = plot_importance(x, ...),
    structure  = plot_tree_structure(tree, ...),
    projection = plot_projection(tree, node = node, ...),
    boundaries = plot_boundaries(tree, ...)
  )

  if (inherits(p, "gtable")) {
    grid::grid.newpage()
    grid::grid.draw(p)
  } else {
    print(p)
  }
  invisible(p)
}
