# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pptree_train_tree_glda <- function(x, y, lambda, seed) {
    .Call('_PPTree_pptree_train_tree_glda', PACKAGE = 'PPTree', x, y, lambda, seed)
}

pptree_train_forest_glda <- function(x, y, size, n_vars, lambda, seed, n_threads) {
    .Call('_PPTree_pptree_train_forest_glda', PACKAGE = 'PPTree', x, y, size, n_vars, lambda, seed, n_threads)
}

pptree_predict <- function(tree, data) {
    .Call('_PPTree_pptree_predict', PACKAGE = 'PPTree', tree, data)
}

pptree_predict_forest <- function(forest, data) {
    .Call('_PPTree_pptree_predict_forest', PACKAGE = 'PPTree', forest, data)
}

pptree_predict_forest_prob <- function(forest, data) {
    .Call('_PPTree_pptree_predict_forest_prob', PACKAGE = 'PPTree', forest, data)
}

pptree_vi_projections_tree <- function(tree, n_vars, scale) {
    .Call('_PPTree_pptree_vi_projections_tree', PACKAGE = 'PPTree', tree, n_vars, scale)
}

pptree_vi_projections_forest <- function(forest, n_vars, scale) {
    .Call('_PPTree_pptree_vi_projections_forest', PACKAGE = 'PPTree', forest, n_vars, scale)
}

pptree_vi_weighted <- function(forest, x, y, scale) {
    .Call('_PPTree_pptree_vi_weighted', PACKAGE = 'PPTree', forest, x, y, scale)
}

pptree_vi_permuted <- function(forest, x, y, seed) {
    .Call('_PPTree_pptree_vi_permuted', PACKAGE = 'PPTree', forest, x, y, seed)
}

pptree_oob_error <- function(forest, x, y) {
    .Call('_PPTree_pptree_oob_error', PACKAGE = 'PPTree', forest, x, y)
}

pptree_tree_node_data <- function(tree, x, y) {
    .Call('_PPTree_pptree_tree_node_data', PACKAGE = 'PPTree', tree, x, y)
}

pptree_boundary_segments <- function(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max) {
    .Call('_PPTree_pptree_boundary_segments', PACKAGE = 'PPTree', tree, var_indices, fixed_values, x_min, x_max, y_min, y_max)
}

pptree_decision_regions <- function(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max) {
    .Call('_PPTree_pptree_decision_regions', PACKAGE = 'PPTree', tree, var_indices, fixed_values, x_min, x_max, y_min, y_max)
}

pptree_tree_layout <- function(tree) {
    .Call('_PPTree_pptree_tree_layout', PACKAGE = 'PPTree', tree)
}

