# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pptree_train_glda <- function(data, groups, lambda) {
    .Call('_PPTree_pptree_train_glda', PACKAGE = 'PPTree', data, groups, lambda)
}

pptree_train_forest_glda <- function(data, groups, size, n_vars, lambda, n_threads) {
    .Call('_PPTree_pptree_train_forest_glda', PACKAGE = 'PPTree', data, groups, size, n_vars, lambda, n_threads)
}

pptree_predict <- function(tree, data) {
    .Call('_PPTree_pptree_predict', PACKAGE = 'PPTree', tree, data)
}

pptree_predict_forest <- function(forest, data) {
    .Call('_PPTree_pptree_predict_forest', PACKAGE = 'PPTree', forest, data)
}

pptree_variable_importance <- function(tree) {
    .Call('_PPTree_pptree_variable_importance', PACKAGE = 'PPTree', tree)
}

pptree_forest_variable_importance <- function(forest) {
    .Call('_PPTree_pptree_forest_variable_importance', PACKAGE = 'PPTree', forest)
}

pptree_confusion_matrix <- function(tree) {
    .Call('_PPTree_pptree_confusion_matrix', PACKAGE = 'PPTree', tree)
}

pptree_forest_confusion_matrix <- function(forest) {
    .Call('_PPTree_pptree_forest_confusion_matrix', PACKAGE = 'PPTree', forest)
}

