fail_fast: false
repos:
  - repo: local
    hooks:
      - id: qa-format
        name: Format (uncrustify)
        entry: make format
        language: system
      - id: qa-lint
        name: Lint (cppcheck)
        entry: make lint
        language: system
      - id: qa-test
        name: Tests (ctest)
        entry: make test
        language: system
