version: '3.8'
services:
  ubuntu:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/pptree
      - /pptree/.build
      - /pptree/.debug
      - /pptree/.tools
    tty: true
    stdin_open: true