// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ppforest2.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ppforest2_has_openmp
bool ppforest2_has_openmp();
RcppExport SEXP _ppforest2_ppforest2_has_openmp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ppforest2_has_openmp());
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_train_tree_pda
Tree ppforest2_train_tree_pda(FeatureMatrix x, ResponseVector y, const float lambda, const int seed);
RcppExport SEXP _ppforest2_ppforest2_train_tree_pda(SEXP xSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_train_tree_pda(x, y, lambda, seed));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_train_forest_pda
Forest ppforest2_train_forest_pda(FeatureMatrix x, ResponseVector y, const int size, const int n_vars, const float lambda, const int seed, SEXP n_threads, const int max_retries);
RcppExport SEXP _ppforest2_ppforest2_train_forest_pda(SEXP xSEXP, SEXP ySEXP, SEXP sizeSEXP, SEXP n_varsSEXP, SEXP lambdaSEXP, SEXP seedSEXP, SEXP n_threadsSEXP, SEXP max_retriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_retries(max_retriesSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_train_forest_pda(x, y, size, n_vars, lambda, seed, n_threads, max_retries));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_tree
ResponseVector ppforest2_predict_tree(const Tree& tree, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_tree(SEXP treeSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_tree(tree, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_tree_forest
ResponseVector ppforest2_predict_tree_forest(const Forest& forest, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_tree_forest(SEXP forestSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_tree_forest(forest, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_tree_prob
FeatureMatrix ppforest2_predict_tree_prob(const Tree& tree, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_tree_prob(SEXP treeSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_tree_prob(tree, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_forest_prob
FeatureMatrix ppforest2_predict_forest_prob(const Forest& forest, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_forest_prob(SEXP forestSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_forest_prob(forest, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_projections_tree
FeatureVector ppforest2_vi_projections_tree(const Tree& tree, int n_vars, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_projections_tree(SEXP treeSEXP, SEXP n_varsSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_projections_tree(tree, n_vars, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_projections_forest
FeatureVector ppforest2_vi_projections_forest(const Forest& forest, int n_vars, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_projections_forest(SEXP forestSEXP, SEXP n_varsSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_projections_forest(forest, n_vars, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_weighted_forest
FeatureVector ppforest2_vi_weighted_forest(const Forest& forest, const FeatureMatrix& x, ResponseVector y, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_weighted_forest(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_weighted_forest(forest, x, y, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_permuted_forest
FeatureVector ppforest2_vi_permuted_forest(const Forest& forest, const FeatureMatrix& x, ResponseVector y, int seed);
RcppExport SEXP _ppforest2_ppforest2_vi_permuted_forest(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_permuted_forest(forest, x, y, seed));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_oob_error
double ppforest2_oob_error(const Forest& forest, const FeatureMatrix& x, ResponseVector y);
RcppExport SEXP _ppforest2_ppforest2_oob_error(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_oob_error(forest, x, y));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_oob_predict
ResponseVector ppforest2_oob_predict(const Forest& forest, const FeatureMatrix& x);
RcppExport SEXP _ppforest2_ppforest2_oob_predict(SEXP forestSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_oob_predict(forest, x));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_tree_node_data
Rcpp::List ppforest2_tree_node_data(const Tree& tree, const FeatureMatrix& x, ResponseVector y);
RcppExport SEXP _ppforest2_ppforest2_tree_node_data(SEXP treeSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_tree_node_data(tree, x, y));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_boundary_segments
Rcpp::DataFrame ppforest2_boundary_segments(const Tree& tree, Rcpp::IntegerVector var_indices, Rcpp::NumericVector fixed_values, double x_min, double x_max, double y_min, double y_max);
RcppExport SEXP _ppforest2_ppforest2_boundary_segments(SEXP treeSEXP, SEXP var_indicesSEXP, SEXP fixed_valuesSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type var_indices(var_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_boundary_segments(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_decision_regions
Rcpp::List ppforest2_decision_regions(const Tree& tree, Rcpp::IntegerVector var_indices, Rcpp::NumericVector fixed_values, double x_min, double x_max, double y_min, double y_max);
RcppExport SEXP _ppforest2_ppforest2_decision_regions(SEXP treeSEXP, SEXP var_indicesSEXP, SEXP fixed_valuesSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type var_indices(var_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_decision_regions(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_tree_layout
Rcpp::List ppforest2_tree_layout(const Tree& tree);
RcppExport SEXP _ppforest2_ppforest2_tree_layout(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_tree_layout(tree));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_save_tree_json
std::string ppforest2_save_tree_json(const Tree& tree, Rcpp::CharacterVector groups, Rcpp::List vi, Rcpp::List training_spec, int seed, bool include_metrics, int n_obs, int n_features, SEXP feature_names);
RcppExport SEXP _ppforest2_ppforest2_save_tree_json(SEXP treeSEXP, SEXP groupsSEXP, SEXP viSEXP, SEXP training_specSEXP, SEXP seedSEXP, SEXP include_metricsSEXP, SEXP n_obsSEXP, SEXP n_featuresSEXP, SEXP feature_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vi(viSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type training_spec(training_specSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type include_metrics(include_metricsSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type n_features(n_featuresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type feature_names(feature_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_save_tree_json(tree, groups, vi, training_spec, seed, include_metrics, n_obs, n_features, feature_names));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_save_forest_json
std::string ppforest2_save_forest_json(const Forest& forest, Rcpp::CharacterVector groups, Rcpp::List vi, Rcpp::List training_spec, int seed, double oob_error, bool include_metrics, int n_obs, int n_features, SEXP feature_names);
RcppExport SEXP _ppforest2_ppforest2_save_forest_json(SEXP forestSEXP, SEXP groupsSEXP, SEXP viSEXP, SEXP training_specSEXP, SEXP seedSEXP, SEXP oob_errorSEXP, SEXP include_metricsSEXP, SEXP n_obsSEXP, SEXP n_featuresSEXP, SEXP feature_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vi(viSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type training_spec(training_specSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type oob_error(oob_errorSEXP);
    Rcpp::traits::input_parameter< bool >::type include_metrics(include_metricsSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type n_features(n_featuresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type feature_names(feature_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_save_forest_json(forest, groups, vi, training_spec, seed, oob_error, include_metrics, n_obs, n_features, feature_names));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_load_json_meta
Rcpp::List ppforest2_load_json_meta(const std::string& json_str);
RcppExport SEXP _ppforest2_ppforest2_load_json_meta(SEXP json_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type json_str(json_strSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_load_json_meta(json_str));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_tree_from_json
Tree ppforest2_tree_from_json(const std::string& json_str);
RcppExport SEXP _ppforest2_ppforest2_tree_from_json(SEXP json_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type json_str(json_strSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_tree_from_json(json_str));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_forest_from_json
Forest ppforest2_forest_from_json(const std::string& json_str);
RcppExport SEXP _ppforest2_ppforest2_forest_from_json(SEXP json_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type json_str(json_strSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_forest_from_json(json_str));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ppforest2_ppforest2_has_openmp", (DL_FUNC) &_ppforest2_ppforest2_has_openmp, 0},
    {"_ppforest2_ppforest2_train_tree_pda", (DL_FUNC) &_ppforest2_ppforest2_train_tree_pda, 4},
    {"_ppforest2_ppforest2_train_forest_pda", (DL_FUNC) &_ppforest2_ppforest2_train_forest_pda, 8},
    {"_ppforest2_ppforest2_predict_tree", (DL_FUNC) &_ppforest2_ppforest2_predict_tree, 2},
    {"_ppforest2_ppforest2_predict_tree_forest", (DL_FUNC) &_ppforest2_ppforest2_predict_tree_forest, 2},
    {"_ppforest2_ppforest2_predict_tree_prob", (DL_FUNC) &_ppforest2_ppforest2_predict_tree_prob, 2},
    {"_ppforest2_ppforest2_predict_forest_prob", (DL_FUNC) &_ppforest2_ppforest2_predict_forest_prob, 2},
    {"_ppforest2_ppforest2_vi_projections_tree", (DL_FUNC) &_ppforest2_ppforest2_vi_projections_tree, 3},
    {"_ppforest2_ppforest2_vi_projections_forest", (DL_FUNC) &_ppforest2_ppforest2_vi_projections_forest, 3},
    {"_ppforest2_ppforest2_vi_weighted_forest", (DL_FUNC) &_ppforest2_ppforest2_vi_weighted_forest, 4},
    {"_ppforest2_ppforest2_vi_permuted_forest", (DL_FUNC) &_ppforest2_ppforest2_vi_permuted_forest, 4},
    {"_ppforest2_ppforest2_oob_error", (DL_FUNC) &_ppforest2_ppforest2_oob_error, 3},
    {"_ppforest2_ppforest2_oob_predict", (DL_FUNC) &_ppforest2_ppforest2_oob_predict, 2},
    {"_ppforest2_ppforest2_tree_node_data", (DL_FUNC) &_ppforest2_ppforest2_tree_node_data, 3},
    {"_ppforest2_ppforest2_boundary_segments", (DL_FUNC) &_ppforest2_ppforest2_boundary_segments, 7},
    {"_ppforest2_ppforest2_decision_regions", (DL_FUNC) &_ppforest2_ppforest2_decision_regions, 7},
    {"_ppforest2_ppforest2_tree_layout", (DL_FUNC) &_ppforest2_ppforest2_tree_layout, 1},
    {"_ppforest2_ppforest2_save_tree_json", (DL_FUNC) &_ppforest2_ppforest2_save_tree_json, 9},
    {"_ppforest2_ppforest2_save_forest_json", (DL_FUNC) &_ppforest2_ppforest2_save_forest_json, 10},
    {"_ppforest2_ppforest2_load_json_meta", (DL_FUNC) &_ppforest2_ppforest2_load_json_meta, 1},
    {"_ppforest2_ppforest2_tree_from_json", (DL_FUNC) &_ppforest2_ppforest2_tree_from_json, 1},
    {"_ppforest2_ppforest2_forest_from_json", (DL_FUNC) &_ppforest2_ppforest2_forest_from_json, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppforest2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
