// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ppforest2.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ppforest2_has_openmp
bool ppforest2_has_openmp();
RcppExport SEXP _ppforest2_ppforest2_has_openmp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ppforest2_has_openmp());
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_train_tree_glda
Tree ppforest2_train_tree_glda(FeatureMatrix x, ResponseVector y, const float lambda, const int seed);
RcppExport SEXP _ppforest2_ppforest2_train_tree_glda(SEXP xSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_train_tree_glda(x, y, lambda, seed));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_train_forest_glda
Forest ppforest2_train_forest_glda(FeatureMatrix x, ResponseVector y, const int size, const int n_vars, const float lambda, const int seed, SEXP n_threads);
RcppExport SEXP _ppforest2_ppforest2_train_forest_glda(SEXP xSEXP, SEXP ySEXP, SEXP sizeSEXP, SEXP n_varsSEXP, SEXP lambdaSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_train_forest_glda(x, y, size, n_vars, lambda, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict
ResponseVector ppforest2_predict(const Tree& tree, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict(SEXP treeSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict(tree, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_forest
ResponseVector ppforest2_predict_forest(const Forest& forest, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_forest(SEXP forestSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_forest(forest, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_predict_forest_prob
FeatureMatrix ppforest2_predict_forest_prob(const Forest& forest, const FeatureMatrix& data);
RcppExport SEXP _ppforest2_ppforest2_predict_forest_prob(SEXP forestSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_predict_forest_prob(forest, data));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_projections_tree
FeatureVector ppforest2_vi_projections_tree(const Tree& tree, int n_vars, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_projections_tree(SEXP treeSEXP, SEXP n_varsSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_projections_tree(tree, n_vars, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_projections_forest
FeatureVector ppforest2_vi_projections_forest(const Forest& forest, int n_vars, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_projections_forest(SEXP forestSEXP, SEXP n_varsSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_projections_forest(forest, n_vars, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_weighted
FeatureVector ppforest2_vi_weighted(const Forest& forest, const FeatureMatrix& x, const ResponseVector& y, const FeatureVector& scale);
RcppExport SEXP _ppforest2_ppforest2_vi_weighted(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const ResponseVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const FeatureVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_weighted(forest, x, y, scale));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_vi_permuted
FeatureVector ppforest2_vi_permuted(const Forest& forest, const FeatureMatrix& x, const ResponseVector& y, int seed);
RcppExport SEXP _ppforest2_ppforest2_vi_permuted(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const ResponseVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_vi_permuted(forest, x, y, seed));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_oob_error
double ppforest2_oob_error(const Forest& forest, const FeatureMatrix& x, const ResponseVector& y);
RcppExport SEXP _ppforest2_ppforest2_oob_error(SEXP forestSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const ResponseVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_oob_error(forest, x, y));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_tree_node_data
Rcpp::List ppforest2_tree_node_data(const Tree& tree, const FeatureMatrix& x, const ResponseVector& y);
RcppExport SEXP _ppforest2_ppforest2_tree_node_data(SEXP treeSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const ResponseVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_tree_node_data(tree, x, y));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_boundary_segments
Rcpp::DataFrame ppforest2_boundary_segments(const Tree& tree, Rcpp::IntegerVector var_indices, Rcpp::NumericVector fixed_values, double x_min, double x_max, double y_min, double y_max);
RcppExport SEXP _ppforest2_ppforest2_boundary_segments(SEXP treeSEXP, SEXP var_indicesSEXP, SEXP fixed_valuesSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type var_indices(var_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_boundary_segments(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_decision_regions
Rcpp::List ppforest2_decision_regions(const Tree& tree, Rcpp::IntegerVector var_indices, Rcpp::NumericVector fixed_values, double x_min, double x_max, double y_min, double y_max);
RcppExport SEXP _ppforest2_ppforest2_decision_regions(SEXP treeSEXP, SEXP var_indicesSEXP, SEXP fixed_valuesSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type var_indices(var_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_decision_regions(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max));
    return rcpp_result_gen;
END_RCPP
}
// ppforest2_tree_layout
Rcpp::List ppforest2_tree_layout(const Tree& tree);
RcppExport SEXP _ppforest2_ppforest2_tree_layout(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(ppforest2_tree_layout(tree));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ppforest2_ppforest2_has_openmp", (DL_FUNC) &_ppforest2_ppforest2_has_openmp, 0},
    {"_ppforest2_ppforest2_train_tree_glda", (DL_FUNC) &_ppforest2_ppforest2_train_tree_glda, 4},
    {"_ppforest2_ppforest2_train_forest_glda", (DL_FUNC) &_ppforest2_ppforest2_train_forest_glda, 7},
    {"_ppforest2_ppforest2_predict", (DL_FUNC) &_ppforest2_ppforest2_predict, 2},
    {"_ppforest2_ppforest2_predict_forest", (DL_FUNC) &_ppforest2_ppforest2_predict_forest, 2},
    {"_ppforest2_ppforest2_predict_forest_prob", (DL_FUNC) &_ppforest2_ppforest2_predict_forest_prob, 2},
    {"_ppforest2_ppforest2_vi_projections_tree", (DL_FUNC) &_ppforest2_ppforest2_vi_projections_tree, 3},
    {"_ppforest2_ppforest2_vi_projections_forest", (DL_FUNC) &_ppforest2_ppforest2_vi_projections_forest, 3},
    {"_ppforest2_ppforest2_vi_weighted", (DL_FUNC) &_ppforest2_ppforest2_vi_weighted, 4},
    {"_ppforest2_ppforest2_vi_permuted", (DL_FUNC) &_ppforest2_ppforest2_vi_permuted, 4},
    {"_ppforest2_ppforest2_oob_error", (DL_FUNC) &_ppforest2_ppforest2_oob_error, 3},
    {"_ppforest2_ppforest2_tree_node_data", (DL_FUNC) &_ppforest2_ppforest2_tree_node_data, 3},
    {"_ppforest2_ppforest2_boundary_segments", (DL_FUNC) &_ppforest2_ppforest2_boundary_segments, 7},
    {"_ppforest2_ppforest2_decision_regions", (DL_FUNC) &_ppforest2_ppforest2_decision_regions, 7},
    {"_ppforest2_ppforest2_tree_layout", (DL_FUNC) &_ppforest2_ppforest2_tree_layout, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppforest2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
