// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/PPTree.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pptree_train_glda
Tree pptree_train_glda(FeatureMatrix x, ResponseVector y, const float lambda);
RcppExport SEXP _PPTree_pptree_train_glda(SEXP xSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pptree_train_glda(x, y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// pptree_train_forest_glda
Forest pptree_train_forest_glda(FeatureMatrix x, ResponseVector y, const int size, const int n_vars, const float lambda, SEXP n_threads);
RcppExport SEXP _PPTree_pptree_train_forest_glda(SEXP xSEXP, SEXP ySEXP, SEXP sizeSEXP, SEXP n_varsSEXP, SEXP lambdaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< FeatureMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< ResponseVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< const float >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pptree_train_forest_glda(x, y, size, n_vars, lambda, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pptree_predict
ResponseVector pptree_predict(const Tree& tree, const FeatureMatrix& data);
RcppExport SEXP _PPTree_pptree_predict(SEXP treeSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Tree& >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(pptree_predict(tree, data));
    return rcpp_result_gen;
END_RCPP
}
// pptree_predict_forest
ResponseVector pptree_predict_forest(const Forest& forest, const FeatureMatrix& data);
RcppExport SEXP _PPTree_pptree_predict_forest(SEXP forestSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Forest& >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< const FeatureMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(pptree_predict_forest(forest, data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PPTree_pptree_train_glda", (DL_FUNC) &_PPTree_pptree_train_glda, 3},
    {"_PPTree_pptree_train_forest_glda", (DL_FUNC) &_PPTree_pptree_train_forest_glda, 6},
    {"_PPTree_pptree_predict", (DL_FUNC) &_PPTree_pptree_predict, 2},
    {"_PPTree_pptree_predict_forest", (DL_FUNC) &_PPTree_pptree_predict_forest, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PPTree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
