#pragma once

#include <random>
#include "stats/Stats.hpp"

#include "utils/Invariant.hpp"

namespace pptree::stats {
  /**
   * @brief Discrete uniform random integer generator over [min, max].
   *
   * All random integers are produced via Lemire's nearly-divisionless
   * method, which replaces the classical modulo reduction with a
   * multiply-and-shift, falling back to rejection sampling only when
   * needed to eliminate bias.  This is both faster and provably
   * unbiased.
   *
   * The distinct() method builds on this by performing a Fisher-Yates
   * (Knuth) shuffle to sample without replacement — the foundation
   * of bootstrap sampling and random variable selection in forests.
   *
   * @note This class is used instead of std::uniform_int_distribution
   *       to guarantee identical output across compilers and platforms.
   *
   * @see https://arxiv.org/abs/1805.10941
   */
  class Uniform {
    private:
      int min;
      int max;

      /**
       * @brief Generate an unbiased random integer in [0, s) via Lemire's method.
       *
       * Computes a 64-bit product x·s where x is a 32-bit pcg32 output.
       * The upper 32 bits of the product give the result.  When the lower
       * 32 bits (the remainder analogue) fall below s, rejection sampling
       * kicks in to correct the bias — but this happens with probability
       * < s / 2³², so for small s it is essentially free.
       *
       * @param s    Exclusive upper bound (must be > 0).
       * @param rng  Random number generator (pcg32).
       * @return     Uniformly distributed integer in [0, s−1].
       *
       * @see Lemire, "Fast Random Integer Generation in an Interval"
       *      (ACM TOMS, 2019). https://arxiv.org/abs/1805.10941
       */
      uint32_t gen_lemire(uint32_t s, RNG &rng) const {
        uint32_t x = rng();
        uint64_t m = static_cast<uint64_t>(x) * s;
        uint32_t l = static_cast<uint32_t>(m);

        if (l < s) {
          uint32_t t = -s % s;

          while (l < t) {
            x = rng();
            m = static_cast<uint64_t>(x) * s;
            l = static_cast<uint32_t>(m);
          }
        }

        uint32_t result = m >> 32;

        invariant(result >= 0 && result < s, "Uniform::gen_lemire: Invalid result generated by gen_lemire");

        return result;
      }

    public:
      /**
       * @brief Construct a uniform integer generator over [min, max].
       *
       * @param min  Inclusive lower bound (must be ≥ 0).
       * @param max  Inclusive upper bound (must be ≥ min).
       */
      Uniform(int min, int max) : min(min), max(max) {
        invariant(min >= 0, "Uniform: min must be greater than or equal to 0");
        invariant(min <= max, "Uniform: min must be less than or equal to max");
        invariant(max < std::numeric_limits<int>::max(), "Uniform: max must be less than the maximum value of an int");
      }

      /**
       * @brief Generate a single uniform random integer in [min, max].
       *
       * @param rng  Random number generator (pcg32).
       * @return     Uniformly distributed integer in [min, max].
       */
      int operator()(RNG &rng) const {
        return min + gen_lemire(max + 1 - min, rng);
      }

      /**
       * @brief Generate multiple uniform random integers (with replacement).
       *
       * @param count  Number of samples to generate.
       * @param rng    Random number generator (pcg32).
       * @return       Vector of @p count i.i.d. integers from [min, max].
       */
      std::vector<int> operator()(int count, RNG &rng) const {
        std::vector<int> result(count);

        for (int i = 0; i < count; i++) {
          result[i] = operator()(rng);
        }

        return result;
      }

      /**
       * @brief Sample without replacement from [min, max].
       *
       * Implements the Fisher-Yates (Knuth) shuffle: fills a vector
       * with [min, max], shuffles it using gen_lemire() for each swap,
       * and returns the first @p count elements.  The result is a
       * uniformly distributed subset of size @p count with no repeats.
       *
       * This is the method used by DRUniformStrategy and bootstrap
       * sampling, ensuring reproducible variable selection across
       * platforms.
       *
       * @param count  Number of distinct integers to draw (≤ range size).
       * @param rng    Random number generator (pcg32).
       * @return       Vector of @p count distinct integers from [min, max].
       */
      std::vector<int> distinct(int count, RNG &rng) {
        int range_size = max - min + 1;

        invariant(count <= range_size, "Uniform::distinct: count must be less than or equal to the number of unique values in the range");
        invariant(count >= 0, "Uniform::distinct: count must be greater than or equal to 0");

        std::vector<int> values(range_size);
        std::iota(values.begin(), values.end(), min);

        for (int i = range_size - 1; i >= 0; i--) {
          int j = gen_lemire(i + 1, rng);

          invariant(j >= 0 && j < range_size, "Uniform::distinct: Invalid index generated by gen_lemire");

          std::swap(values[i], values[j]);
        }

        return std::vector<int>(values.begin(), values.begin() + count);
      }
  };
}
