# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ppforest2_has_openmp <- function() {
    .Call('_ppforest2_ppforest2_has_openmp', PACKAGE = 'ppforest2')
}

ppforest2_train_tree_glda <- function(x, y, lambda, seed) {
    .Call('_ppforest2_ppforest2_train_tree_glda', PACKAGE = 'ppforest2', x, y, lambda, seed)
}

ppforest2_train_forest_glda <- function(x, y, size, n_vars, lambda, seed, n_threads, max_retries = 3L) {
    .Call('_ppforest2_ppforest2_train_forest_glda', PACKAGE = 'ppforest2', x, y, size, n_vars, lambda, seed, n_threads, max_retries)
}

ppforest2_predict <- function(tree, data) {
    .Call('_ppforest2_ppforest2_predict', PACKAGE = 'ppforest2', tree, data)
}

ppforest2_predict_forest <- function(forest, data) {
    .Call('_ppforest2_ppforest2_predict_forest', PACKAGE = 'ppforest2', forest, data)
}

ppforest2_predict_forest_prob <- function(forest, data) {
    .Call('_ppforest2_ppforest2_predict_forest_prob', PACKAGE = 'ppforest2', forest, data)
}

ppforest2_vi_projections_tree <- function(tree, n_vars, scale) {
    .Call('_ppforest2_ppforest2_vi_projections_tree', PACKAGE = 'ppforest2', tree, n_vars, scale)
}

ppforest2_vi_projections_forest <- function(forest, n_vars, scale) {
    .Call('_ppforest2_ppforest2_vi_projections_forest', PACKAGE = 'ppforest2', forest, n_vars, scale)
}

ppforest2_vi_weighted <- function(forest, x, y, scale) {
    .Call('_ppforest2_ppforest2_vi_weighted', PACKAGE = 'ppforest2', forest, x, y, scale)
}

ppforest2_vi_permuted <- function(forest, x, y, seed) {
    .Call('_ppforest2_ppforest2_vi_permuted', PACKAGE = 'ppforest2', forest, x, y, seed)
}

ppforest2_oob_error <- function(forest, x, y) {
    .Call('_ppforest2_ppforest2_oob_error', PACKAGE = 'ppforest2', forest, x, y)
}

ppforest2_tree_node_data <- function(tree, x, y) {
    .Call('_ppforest2_ppforest2_tree_node_data', PACKAGE = 'ppforest2', tree, x, y)
}

ppforest2_boundary_segments <- function(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max) {
    .Call('_ppforest2_ppforest2_boundary_segments', PACKAGE = 'ppforest2', tree, var_indices, fixed_values, x_min, x_max, y_min, y_max)
}

ppforest2_decision_regions <- function(tree, var_indices, fixed_values, x_min, x_max, y_min, y_max) {
    .Call('_ppforest2_ppforest2_decision_regions', PACKAGE = 'ppforest2', tree, var_indices, fixed_values, x_min, x_max, y_min, y_max)
}

ppforest2_tree_layout <- function(tree) {
    .Call('_ppforest2_ppforest2_tree_layout', PACKAGE = 'ppforest2', tree)
}

ppforest2_save_tree_json <- function(tree, classes, vi, training_spec, seed, include_metrics) {
    .Call('_ppforest2_ppforest2_save_tree_json', PACKAGE = 'ppforest2', tree, classes, vi, training_spec, seed, include_metrics)
}

ppforest2_save_forest_json <- function(forest, classes, vi, training_spec, seed, oob_error, include_metrics) {
    .Call('_ppforest2_ppforest2_save_forest_json', PACKAGE = 'ppforest2', forest, classes, vi, training_spec, seed, oob_error, include_metrics)
}

ppforest2_load_json_meta <- function(json_str) {
    .Call('_ppforest2_ppforest2_load_json_meta', PACKAGE = 'ppforest2', json_str)
}

ppforest2_tree_from_json <- function(json_str) {
    .Call('_ppforest2_ppforest2_tree_from_json', PACKAGE = 'ppforest2', json_str)
}

ppforest2_forest_from_json <- function(json_str) {
    .Call('_ppforest2_ppforest2_forest_from_json', PACKAGE = 'ppforest2', json_str)
}

