name: Run R Package Check
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - run: sudo apt install build-essential libcurl4-openssl-dev libxml2-dev libssl-dev libfribidi-dev libfreetype6-dev libharfbuzz-dev libfontconfig1-dev libpng-dev libtiff5-dev libgit2-dev
      - run: sudo make r-install-deps
      - run: make r-check
      - name: Show Install Logs
        if: failure()
        run: cat PPtree.Rcheck/00install.out
  Mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - run: make r-install-deps
      - run: make r-check
      - name: Show Install Logs
        if: failure()
        run: cat PPtree.Rcheck/00install.out
  MacOpenMP:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - run: brew install libomp
      - run: make r-install-deps
      - run: make r-check
      - name: Show Install Logs
        if: failure()
        run: cat PPtree.Rcheck/00install.out
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTeX
      - run: make r-install-deps
      - run: make r-check
      - name: Show Install Logs
        if: failure()
        run: cat PPtree.Rcheck/00install.out

