name: Run Formatter
on: push
jobs:
  Uncrustify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - run: conan profile detect
      - run: make install && source _conan/conanbuild.sh && make format
