name: Run R Package Check
on: push
jobs:
  RCMDCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - run: conan profile detect
      - run: make install && source _conan/conanbuild.sh && make r-check
