name: Run Analyze
on: push
jobs:
  CppCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dev tools
        uses: actions/cache@v4
        with:
          path: .tools
          key: ${{ runner.os }}-tools-${{ hashFiles('tools/CMakeLists.txt') }}
      - run: make install-tools
      - run: make analyze
